#!/bin/bash

TARGET=$1
LINK_NAME=$2
TYPE=$3

ACTUAL_TARGET=$(grep "^$TARGET" /root/devices.map | awk -F "=" '{print $2}')
if [ -z "$ACTUAL_TARGET" ]; then
    echo "Error: no device found for $TARGET in /root/devices.map" >&2
    exit 1
fi

LINK_NAME_REPLACED=$(echo "$LINK_NAME" | sed -e "s|^/||" -e "s|/|-|g")
mkdir -p "$LINK_NAME"

MNTFILE="/usr/lib/systemd/system/${LINK_NAME_REPLACED}.mount"
AUTOMNTFILE="/usr/lib/systemd/system/${LINK_NAME_REPLACED}.automount"

cat > "$MNTFILE" << EOF
[Unit]
Description=Shared dir from HV
After=multi-user.target
[Mount]
What=$ACTUAL_TARGET
Where=$LINK_NAME
Type=virtiofs
[Install]
WantedBy=multi-user.target
EOF

cat > "$AUTOMNTFILE" << EOF
[Unit]
Description=Automount $LINK_NAME
ConditionPathExists=$LINK_NAME
[Automount]
Where=$LINK_NAME
TimeoutIdleSec=10
[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable "${LINK_NAME_REPLACED}.mount"
systemctl start "${LINK_NAME_REPLACED}.mount"
